exports.newspaperConfig = {
  theBangladeshToday: {
    leading: "https://thebangladeshtoday.com/",
    national: "https://thebangladeshtoday.com/?cat=29",
    international: "https://thebangladeshtoday.com/?cat=2",
    politics: "https://thebangladeshtoday.com/?cat=28",
    business: "https://thebangladeshtoday.com/?cat=30",
    sports: "https://thebangladeshtoday.com/?cat=5",
    entertainment: "https://thebangladeshtoday.com/?cat=4",
    feature: "https://thebangladeshtoday.com/?cat=6",
  },
  // tbsNews: {
  //   leading: "https://www.tbsnews.net/",
  // },
  // tbsNews: "https://www.tbsnews.net/",
  // observerBD: "https://www.observerbd.com/",
  // dailySun: "https://www.daily-sun.com/",
  // dhakaTribune: "https://www.dhakatribune.com/",
  // newAgeBD: "https://www.newagebd.net/",
  // newNation: "https://newnation.live/",
  // theDailyStar: "https://www.thedailystar.net/",
  // alokitoBangladesh: "https://www.alokitobangladesh.com/",
  // amadershomoy: "https://www.dainikamadershomoy.com/",
  // amarBarta: "https://www.amarbarta.com/",
  // bdPratidin: "https://www.bd-pratidin.com/",
  // bhorerKagoj: "https://www.bhorerkagoj.com/",
  // bonikBarta: "https://bonikbarta.net/",
  // dhakaTimes24: "https://www.dhakatimes24.com/",
  // deshRupantor: "https://www.deshrupantor.com/",
  // dailyInqilab: "https://dailyinqilab.com/",
  // ittefaq: "https://www.ittefaq.com.bd/",
  // jaiJaiDin: "https://www.jaijaidinbd.com/",
  // dailyJanakantha: "https://www.dailyjanakantha.com/",
  // jugantor: "https://www.jugantor.com/",
  // kalbela: "https://www.kalbela.com/",
  // kalerKantho: "https://www.kalerkantho.com/",
  // manabZamin: "https://mzamin.com/",
  // manobKantha: "https://www.manobkantha.com.bd/",
  // dailyNayaDiganta: "https://www.dailynayadiganta.com/",
  // prothomAlo: "https://www.prothomalo.com/",
  // protidinerSangbad: "https://www.protidinersangbad.com/",
  // samakal: "https://samakal.com/",
  // dailySangram: "https://dailysangram.com/",
  // shomoyEralo: "https://www.shomoyeralo.com/",
  // sangbad: "https://sangbad.net.bd/",
};
