exports.newspaperConfig = {
  // theBangladeshToday: {
  //   leading: "https://thebangladeshtoday.com/",
  //   national: "https://thebangladeshtoday.com/?cat=29",
  //   international: "https://thebangladeshtoday.com/?cat=2",
  //   politics: "https://thebangladeshtoday.com/?cat=28",
  //   business: "https://thebangladeshtoday.com/?cat=30",
  //   sports: "https://thebangladeshtoday.com/?cat=5",
  //   entertainment: "https://thebangladeshtoday.com/?cat=4",
  //   feature: "https://thebangladeshtoday.com/?cat=6",
  // },

  // tbsNews: {
  //   leading: "https://www.tbsnews.net/",
  //   national: "https://www.tbsnews.net/bangladesh",
  //   international: "https://www.tbsnews.net/world",
  //   politics: "https://www.tbsnews.net/bangladesh/politics",
  //   business: "https://www.tbsnews.net/economy",
  //   sports: "https://www.tbsnews.net/sports",
  //   feature: "https://www.tbsnews.net/features",
  //   entertainment: "https://www.tbsnews.net/splash",

  //   opinion: "https://www.tbsnews.net/thoughts",
  //   tech: "https://www.tbsnews.net/tech",
  //   health: "https://www.tbsnews.net/bangladesh/health",
  //   crime: "https://www.tbsnews.net/bangladesh/crime",
  // },

  // observerBD: {
  //   leading: "https://www.observerbd.com/",
  //   national: "https://www.observerbd.com/cat.php?cd=186",
  //   international: "https://www.observerbd.com/cat.php?cd=187",
  //   politics: "https://www.observerbd.com/cat.php?cd=229",
  //   business: "https://www.observerbd.com/cat.php?cd=191",
  //   sports: "https://www.observerbd.com/cat.php?cd=185",
  //   countryside: "https://www.observerbd.com/cat.php?cd=188",
  //   education: "https://www.observerbd.com/cat.php?cd=227",
  //   health: "https://www.observerbd.com/cat.php?cd=228",
  //   crime: "https://www.observerbd.com/cat.php?cd=230",
  //   lifestyle: "https://www.observerbd.com/cat.php?cd=204",
  // },

  // dailySun: {
  //   leading: "https://www.daily-sun.com/",
  //   national: "https://www.daily-sun.com/online/national",
  //   international: "https://www.daily-sun.com/online/world",
  //   business: "https://www.daily-sun.com/online/economy",
  //   sports: "https://www.daily-sun.com/online/sports",
  //   feature: "https://www.daily-sun.com/online/feature",
  //   entertainment: "https://www.daily-sun.com/online/entertainment",
  //   tech: "https://www.daily-sun.com/online/sci-tech",

  //   opinion: "https://www.daily-sun.com/online/opinion",
  //   health: "https://www.daily-sun.com/online/health",
  // },

  // dhakaTribune: {
  //   leading: "https://www.dhakatribune.com/",
  //   national: "https://www.dhakatribune.com/bangladesh",
  //   international: "https://www.dhakatribune.com/world",
  //   business: "https://www.dhakatribune.com/business",
  //   sports: "https://www.dhakatribune.com/sport",
  //   entertainment: "https://www.dhakatribune.com/showtime",
  //   tech: "https://www.dhakatribune.com/science-technology-environment",

  //   opinion: "https://www.dhakatribune.com/opinion",
  //   education: "https://www.dhakatribune.com/bangladesh/education",
  //   politics: "https://www.dhakatribune.com/bangladesh/politics",
  //   crime: "https://www.dhakatribune.com/bangladesh/crime",
  // },

  // newAgeBD: {
  //   leading: "https://www.newagebd.net/",
  //   national: "https://www.newagebd.net/articlelist/302/Bangladesh",
  //   international: "https://www.newagebd.net/articlelist/295/World",
  //   business: "https://www.newagebd.net/articlelist/293/Business",
  //   sports: "https://www.newagebd.net/articlelist/291/Sports",
  //   entertainment: "https://www.newagebd.net/articlelist/297/Entertainment",
  //   tech: "https://www.newagebd.net/articlelist/294/Tech",

  //   opinion: "https://www.newagebd.net/articlelist/298/Opinion",
  //   education: "https://www.newagebd.net/articlelist/382/Science",
  //   politics: "https://www.newagebd.net/articlelist/304/Politics",
  //   health: "https://www.newagebd.net/articlelist/378/Health",
  //   countryside: "https://www.newagebd.net/articlelist/305/Country",
  // },

  // newNation: {
  //   leading: "https://newnation.live/",
  //   national: "https://newnation.live/national/",
  //   international: "https://newnation.live/international/",
  //   business: "https://newnation.live/business/",
  //   sports: "https://newnation.live/sports/",
  //   entertainment: "https://newnation.live/category/entertainment/",

  //   opinion: "https://newnation.live/editorial/",
  //   education: "https://newnation.live/life/",
  //   health: "https://newnation.live/health/",
  // },

  // theDailyStar: {
  //   leading: "https://www.thedailystar.net/",
  //   national: "https://www.thedailystar.net/news/bangladesh",
  //   international: "https://www.thedailystar.net/news/world",
  //   business: "https://www.thedailystar.net/business",
  //   sports: "https://www.thedailystar.net/sports",
  //   entertainment: "https://www.thedailystar.net/entertainment",

  //   opinion: "https://www.thedailystar.net/opinion",
  //   feature: "https://www.thedailystar.net/feature",
  //   lifestyle: "https://www.thedailystar.net/life-living",
  //   tech: "https://www.thedailystar.net/tech-startup",
  // },

  // alokitoBangladesh: "https://www.alokitobangladesh.com/",
  // amadershomoy: "https://www.dainikamadershomoy.com/",
  // amarBarta: "https://www.amarbarta.com/",

  // bdPratidin: {
  //   leading: "https://www.bd-pratidin.com/",
  //   national: "https://www.bd-pratidin.com/national",
  //   international: "https://www.bd-pratidin.com/international-news",
  //   business: "https://www.bd-pratidin.com/economy",
  //   sports: "https://www.bd-pratidin.com/sports",
  //   entertainment: "https://www.bd-pratidin.com/entertainment",

  //   opinion: "https://www.bd-pratidin.com/editorial",
  //   lifestyle: "https://www.bd-pratidin.com/life",
  //   countryside: "https://www.bd-pratidin.com/country",
  //   education: "https://www.bd-pratidin.com/science",
  //   religion: "https://www.bd-pratidin.com/islam",
  //   corporate: "https://www.bd-pratidin.com/corporate-corner",
  // },

  // bhorerKagoj: "https://www.bhorerkagoj.com/",
  // bonikBarta: "https://bonikbarta.net/",
  // dhakaTimes24: "https://www.dhakatimes24.com/",
  // deshRupantor: "https://www.deshrupantor.com/",
  // dailyInqilab: "https://dailyinqilab.com/",
  // ittefaq: "https://www.ittefaq.com.bd/",
  // jaiJaiDin: "https://www.jaijaidinbd.com/",
  dailyJanakantha: {
    leading: "https://www.dailyjanakantha.com/",
    national: "https://www.dailyjanakantha.com/national/",
    international: "https://www.dailyjanakantha.com/international/",
    business: "https://www.dailyjanakantha.com/economy/",
    sports: "https://www.dailyjanakantha.com/sports/",
    entertainment: "https://www.dailyjanakantha.com/entertainment/",
    tech: "https://www.dailyjanakantha.com/science-technology/",
    opinion: "https://www.dailyjanakantha.com/opinion/",
    lifestyle: "https://www.dailyjanakantha.com/lifestyle/",
    job: "https://www.dailyjanakantha.com/job/",
    politics: "https://www.dailyjanakantha.com/politics/",
    countryside: "https://www.dailyjanakantha.com/bangladesh/",
    health: "https://www.dailyjanakantha.com/health/",
    education: "https://www.dailyjanakantha.com/education/",
  },
  // dailyJanakantha: "https://www.dailyjanakantha.com/",

  // jugantor: {
  //   leading: "https://www.jugantor.com/",
  //   national: "https://www.jugantor.com/national",
  //   international: "https://www.jugantor.com/international",
  //   business: "https://www.jugantor.com/economics",
  //   sports: "https://www.jugantor.com/sports",
  //   entertainment: "https://www.jugantor.com/entertainment",
  //   tech: "https://www.jugantor.com/tech",
  //   opinion: "https://www.jugantor.com/editorial",
  //   lifestyle: "https://www.jugantor.com/lifestyle",
  //   job: "https://www.jugantor.com/job-seek",
  //   politics: "https://www.jugantor.com/politics",
  //   countryside: "https://www.jugantor.com/country-news",
  //   religion: "https://www.jugantor.com/islam-life",
  //   education: "https://www.jugantor.com/campus",
  // },

  // jugantor: "https://www.jugantor.com/",
  // kalbela: "https://www.kalbela.com/",

  // kalerKantho: {
  //   leading: "https://www.kalerkantho.com/",
  //   national: "https://www.kalerkantho.com/online/national",
  //   international: "https://www.kalerkantho.com/online/world",
  //   business: "https://www.kalerkantho.com/online/business",
  //   sports: "https://www.kalerkantho.com/online/sport",
  //   entertainment: "https://www.kalerkantho.com/online/entertainment",
  //   tech: "https://www.kalerkantho.com/feature/techbishaw",
  //   opinion: "https://www.kalerkantho.com/print-edition/editorial",
  //   lifestyle: "https://www.kalerkantho.com/online/lifestyle",
  //   job: "https://www.kalerkantho.com/feature/chakriache",
  //   politics: "https://www.kalerkantho.com/online/Politics",
  //   countryside: "https://www.kalerkantho.com/online/country-news",
  //   religion: "https://www.kalerkantho.com/online/Islamic-lifestylie",
  // },

  // manabZamin: {
  //   leading: "https://mzamin.com/",
  //   national: "https://mzamin.com/category.php?cat=8",
  //   international: "https://mzamin.com/category.php?cat=5",
  //   business: "https://mzamin.com/category.php?cat=11",
  //   sports: "https://mzamin.com/category.php?cat=4",
  //   entertainment: "https://mzamin.com/category.php?cat=6",
  //   tech: "https://mzamin.com/category.php?cat=15",
  //   opinion: "https://mzamin.com/category.php?cat=14",
  //   health: "https://mzamin.com/category.php?cat=16",
  //   education: "https://mzamin.com/category.php?cat=10",
  //   politics: "https://mzamin.com/category.php?cat=24",
  // },

  // manobKantha: "https://www.manobkantha.com.bd/",

  // dailyNayaDiganta: {
  //   leading: "https://www.dailynayadiganta.com/",
  //   national: "https://www.dailynayadiganta.com/national/1",
  //   international: "https://www.dailynayadiganta.com/international/8",
  //   business: "https://www.dailynayadiganta.com/economics/3",
  //   sports: "https://www.dailynayadiganta.com/sports/11",
  //   entertainment: "https://www.dailynayadiganta.com/entertainment/16",

  //   opinion: "https://www.dailynayadiganta.com/sub-editorial/9",
  //   feature: "https://www.dailynayadiganta.com/feature/12",
  //   lifestyle: "https://www.dailynayadiganta.com/lifestyle/15", // layout is different
  //   politics: "https://www.dailynayadiganta.com/politics/2",
  //   countryside: "https://www.dailynayadiganta.com/country/7",
  //   education: "https://www.dailynayadiganta.com/education/22",
  // },

  // prothomAlo: {
  //   leading: "https://www.prothomalo.com/",
  //   national: "https://www.prothomalo.com/bangladesh",
  //   international: "https://www.prothomalo.com/world",
  //   business: "https://www.prothomalo.com/business",
  //   sports: "https://www.prothomalo.com/sports",
  //   entertainment: "https://www.prothomalo.com/entertainment",

  //   opinion: "https://www.prothomalo.com/opinion",
  //   feature: "",
  //   lifestyle: "https://www.prothomalo.com/lifestyle",
  //   tech: "https://www.prothomalo.com/technology",
  //   job: "https://www.prothomalo.com/chakri",
  //   politics: "https://www.prothomalo.com/politics",
  //   crime: "https://www.prothomalo.com/bangladesh/crime",
  //   education: "https://www.prothomalo.com/education",
  // },

  // protidinerSangbad: "https://www.protidinersangbad.com/",
  // samakal: "https://samakal.com/",
  // dailySangram: "https://dailysangram.com/",
  // shomoyEralo: "https://www.shomoyeralo.com/",
  // sangbad: "https://sangbad.net.bd/",
};
