exports.newspaperConfig = {
  // /** -------------------------
  //  * ENGLISH DAILY NEWSPAPER
  //  * ------------------------- */

  theBangladeshToday: {
    leading: "https://thebangladeshtoday.com/",
    national: "https://thebangladeshtoday.com/?cat=29",
    international: "https://thebangladeshtoday.com/?cat=2",
    politics: "https://thebangladeshtoday.com/?cat=28",
    business: "https://thebangladeshtoday.com/?cat=30",
    sports: "https://thebangladeshtoday.com/?cat=5",
    entertainment: "https://thebangladeshtoday.com/?cat=4",
    feature: "https://thebangladeshtoday.com/?cat=6",
  },
  tbsNews: {
    leading: "https://www.tbsnews.net/",
    national: "https://www.tbsnews.net/bangladesh",
    international: "https://www.tbsnews.net/world",
    politics: "https://www.tbsnews.net/bangladesh/politics",
    business: "https://www.tbsnews.net/economy",
    sports: "https://www.tbsnews.net/sports",
    feature: "https://www.tbsnews.net/features",
    entertainment: "https://www.tbsnews.net/splash",
    opinion: "https://www.tbsnews.net/thoughts",
    tech: "https://www.tbsnews.net/tech",
    health: "https://www.tbsnews.net/bangladesh/health",
    crime: "https://www.tbsnews.net/bangladesh/crime",
  },
  observerBD: {
    leading: "https://www.observerbd.com/",
    national: "https://www.observerbd.com/cat.php?cd=186",
    international: "https://www.observerbd.com/cat.php?cd=187",
    politics: "https://www.observerbd.com/cat.php?cd=229",
    business: "https://www.observerbd.com/cat.php?cd=191",
    sports: "https://www.observerbd.com/cat.php?cd=185",
    countryside: "https://www.observerbd.com/cat.php?cd=188",
    education: "https://www.observerbd.com/cat.php?cd=227",
    health: "https://www.observerbd.com/cat.php?cd=228",
    crime: "https://www.observerbd.com/cat.php?cd=230",
    lifestyle: "https://www.observerbd.com/cat.php?cd=204",
  },
  dailySun: {
    leading: "https://www.daily-sun.com/",
    national: "https://www.daily-sun.com/online/national",
    international: "https://www.daily-sun.com/online/world",
    business: "https://www.daily-sun.com/online/economy",
    sports: "https://www.daily-sun.com/online/sports",
    feature: "https://www.daily-sun.com/online/feature",
    entertainment: "https://www.daily-sun.com/online/entertainment",
    tech: "https://www.daily-sun.com/online/sci-tech",
    opinion: "https://www.daily-sun.com/online/opinion",
    health: "https://www.daily-sun.com/online/health",
  },
  dhakaTribune: {
    leading: "https://www.dhakatribune.com/",
    national: "https://www.dhakatribune.com/bangladesh",
    international: "https://www.dhakatribune.com/world",
    business: "https://www.dhakatribune.com/business",
    sports: "https://www.dhakatribune.com/sport",
    entertainment: "https://www.dhakatribune.com/showtime",
    tech: "https://www.dhakatribune.com/science-technology-environment",
    opinion: "https://www.dhakatribune.com/opinion",
    education: "https://www.dhakatribune.com/bangladesh/education",
    politics: "https://www.dhakatribune.com/bangladesh/politics",
    crime: "https://www.dhakatribune.com/bangladesh/crime",
  },
  newAgeBD: {
    leading: "https://www.newagebd.net/",
    national: "https://www.newagebd.net/articlelist/302/Bangladesh",
    international: "https://www.newagebd.net/articlelist/295/World",
    business: "https://www.newagebd.net/articlelist/293/Business",
    sports: "https://www.newagebd.net/articlelist/291/Sports",
    entertainment: "https://www.newagebd.net/articlelist/297/Entertainment",
    tech: "https://www.newagebd.net/articlelist/294/Tech",
    opinion: "https://www.newagebd.net/articlelist/298/Opinion",
    education: "https://www.newagebd.net/articlelist/382/Science",
    politics: "https://www.newagebd.net/articlelist/304/Politics",
    health: "https://www.newagebd.net/articlelist/378/Health",
    countryside: "https://www.newagebd.net/articlelist/305/Country",
  },
  newNation: {
    leading: "https://newnation.live/",
    national: "https://newnation.live/national/",
    international: "https://newnation.live/international/",
    business: "https://newnation.live/business/",
    sports: "https://newnation.live/sports/",
    entertainment: "https://newnation.live/category/entertainment/",
    opinion: "https://newnation.live/editorial/",
    education: "https://newnation.live/life/",
    health: "https://newnation.live/health/",
  },
  theDailyStar: {
    leading: "https://www.thedailystar.net/",
    national: "https://www.thedailystar.net/news/bangladesh",
    international: "https://www.thedailystar.net/news/world",
    business: "https://www.thedailystar.net/business",
    sports: "https://www.thedailystar.net/sports",
    entertainment: "https://www.thedailystar.net/entertainment",
    opinion: "https://www.thedailystar.net/opinion",
    feature: "https://www.thedailystar.net/feature",
    lifestyle: "https://www.thedailystar.net/life-living",
    tech: "https://www.thedailystar.net/tech-startup",
  },
  theFinancialExpress: {
    leading: "https://thefinancialexpress.com.bd/",
    national: "https://thefinancialexpress.com.bd/national",
    international: "https://thefinancialexpress.com.bd/world",
    business: "https://thefinancialexpress.com.bd/economy",
    sports: "https://thefinancialexpress.com.bd/sports",
    opinion: "https://thefinancialexpress.com.bd/views",
    tech: "https://thefinancialexpress.com.bd/sci-tech",
    lifestyle: "https://thefinancialexpress.com.bd/lifestyle",
    environment: "https://thefinancialexpress.com.bd/environment",
    health: "https://thefinancialexpress.com.bd/health",
    education: "https://thefinancialexpress.com.bd/education",
    editorial: "https://thefinancialexpress.com.bd/editorial",
    countryside: "https://thefinancialexpress.com.bd/page/national/country",
    politics: "https://thefinancialexpress.com.bd/page/national/politics",
    job: "https://thefinancialexpress.com.bd/jobs-and-opportunities",
    stock: "https://thefinancialexpress.com.bd/stock",
    trade: "https://thefinancialexpress.com.bd/trade",
  },

  // /** ------------------------
  //  * BANGLA DAILY NEWSPAPERS
  //  * ------------------------*/

  ajkerPatrika: {
    leading: "https://www.ajkerpatrika.com/",
    national: "https://www.ajkerpatrika.com/national",
    international: "https://www.ajkerpatrika.com/international",
    business: "https://www.ajkerpatrika.com/business",
    sports: "https://www.ajkerpatrika.com/sports",
    entertainment: "https://www.ajkerpatrika.com/entertainment",
    tech: "https://www.ajkerpatrika.com/technology",
    opinion: "https://www.ajkerpatrika.com/op-ed",
    education: "https://www.ajkerpatrika.com/education",
    health: "https://www.ajkerpatrika.com/health",
    lifestyle: "https://www.ajkerpatrika.com/lifestyle",
    politics: "https://www.ajkerpatrika.com/politics",
    countryside: "https://www.ajkerpatrika.com/bangladesh",
    job: "https://www.ajkerpatrika.com/job",
    editorial: "https://www.ajkerpatrika.com/editorial",
    corporate: "https://www.ajkerpatrika.com/corporate",
  },

  alokitoBangladesh: {
    leading: "https://www.alokitobangladesh.com/",
    national: "https://www.alokitobangladesh.com/national",
    international: "https://www.alokitobangladesh.com/interrnational",
    business: "https://www.alokitobangladesh.com/economy",
    sports: "https://www.alokitobangladesh.com/sports",
    entertainment: "https://www.alokitobangladesh.com/entertainment",
    tech: "https://www.alokitobangladesh.com/info-and-technology",
    opinion: "https://www.alokitobangladesh.com/openion",
    education: "https://www.alokitobangladesh.com/education",
    health: "https://www.alokitobangladesh.com/health-treatment",
    lifestyle: "https://www.alokitobangladesh.com/lifestyle",
    politics: "https://www.alokitobangladesh.com/politics",
    literature: "https://www.alokitobangladesh.com/literature",
    countryside: "https://www.alokitobangladesh.com/country-news",
    religion: "https://www.alokitobangladesh.com/islam",
    job: "https://www.alokitobangladesh.com/job-news",
    feature: "https://www.alokitobangladesh.com/feature",
  },

  amadershomoy: {
    leading: "https://www.dainikamadershomoy.com/",
    national: "https://www.dainikamadershomoy.com/category/national",
    international: "https://www.dainikamadershomoy.com/category/international",
    business: "https://www.dainikamadershomoy.com/category/economy",
    sports: "https://www.dainikamadershomoy.com/category/sports",
    entertainment: "https://www.dainikamadershomoy.com/category/entertainment",
    tech: "https://www.dainikamadershomoy.com/category/technology",
    opinion: "https://www.dainikamadershomoy.com/category/shompadiokiyo",
    lifestyle: "https://www.dainikamadershomoy.com/category/lifestyle",
    politics: "https://www.dainikamadershomoy.com/category/all/rajneeti",
    countryside: "https://www.dainikamadershomoy.com/category/sarades",
    feature: "https://www.dainikamadershomoy.com/category/feature",
    education: "https://www.dainikamadershomoy.com/category/education",
    job: "https://www.dainikamadershomoy.com/category/career",
    religion: "https://www.dainikamadershomoy.com/category/religion",
  },

  amarBarta: {
    leading: "https://www.amarbarta.com/"
  },

  bdPratidin: {
    leading: "https://www.bd-pratidin.com/",
    national: "https://www.bd-pratidin.com/national",
    international: "https://www.bd-pratidin.com/international-news",
    business: "https://www.bd-pratidin.com/economy",
    sports: "https://www.bd-pratidin.com/sports",
    entertainment: "https://www.bd-pratidin.com/entertainment",
    opinion: "https://www.bd-pratidin.com/editorial",
    lifestyle: "https://www.bd-pratidin.com/life",
    countryside: "https://www.bd-pratidin.com/country",
    education: "https://www.bd-pratidin.com/science",
    religion: "https://www.bd-pratidin.com/islam",
    corporate: "https://www.bd-pratidin.com/corporate-corner",
  },

  bhorerKagoj: {
    leading: "https://www.bhorerkagoj.com/",
    national: "https://www.bhorerkagoj.com/national",
    international: "https://www.bhorerkagoj.com/international",
    business: "https://www.bhorerkagoj.com/economics",
    sports: "https://www.bhorerkagoj.com/sports",
    entertainment: "https://www.bhorerkagoj.com/entertainment",
    tech: "https://www.bhorerkagoj.com/tech",
    opinion: "https://www.bhorerkagoj.com/opinion",
    lifestyle: "https://www.bhorerkagoj.com/lifestyle",
    countryside: "https://www.bhorerkagoj.com/country",
    feature: "https://www.bhorerkagoj.com/feature",
    education: "https://www.bhorerkagoj.com/education",
    job: "https://www.bhorerkagoj.com/career",
    religion: "https://www.bhorerkagoj.com/religion",
    politics: "https://www.bhorerkagoj.com/politics",
    literature: "https://www.bhorerkagoj.com/literature",
    health: "https://www.bhorerkagoj.com/health",
  },

  bonikBarta: {
    leading: "https://bonikbarta.net/",
  },
  dhakaTimes24: {
   leading: "https://www.dhakatimes24.com/",
  },
  deshRupantor:{
     
    leading: "https://www.deshrupantor.com/",
  },

  dailyInqilab: {
    leading: "https://dailyinqilab.com/",
    national: "https://dailyinqilab.com/national",
    international: "https://dailyinqilab.com/international",
    business: "https://dailyinqilab.com/economy",
    sports: "https://dailyinqilab.com/sports",
    entertainment: "https://dailyinqilab.com/entertainment",
    tech: "https://dailyinqilab.com/ict-and-career",
    opinion: "https://dailyinqilab.com/editorial",
    lifestyle: "https://dailyinqilab.com/lifestyle",
    politics: "https://dailyinqilab.com/politics",
    countryside: "https://dailyinqilab.com/bangladesh",
    health: "https://dailyinqilab.com/health",
    literature: "https://dailyinqilab.com/literature",
  },

  ittefaq: {
    leading: "https://www.ittefaq.com.bd/",
    national: "https://www.ittefaq.com.bd/national",
    international: "https://www.ittefaq.com.bd/world-news",
    business: "https://www.ittefaq.com.bd/business",
    sports: "https://www.ittefaq.com.bd/sports",
    entertainment: "https://www.ittefaq.com.bd/entertainment",
    tech: "https://www.ittefaq.com.bd/tech",
    opinion: "https://www.ittefaq.com.bd/editorial",
    lifestyle: "https://www.ittefaq.com.bd/lifestyle",
    job: "https://www.ittefaq.com.bd/jobs",
    politics: "https://www.ittefaq.com.bd/politics",
    countryside: "https://www.ittefaq.com.bd/country",
    health: "https://www.ittefaq.com.bd/health",
    campus: "https://www.ittefaq.com.bd/campus",
  },

  jaiJaiDin: {
    leading: "https://www.jaijaidinbd.com/",
    national: "https://www.jaijaidinbd.com/national",
    international: "https://www.jaijaidinbd.com/international",
    business: "https://www.jaijaidinbd.com/economics",
    sports: "https://www.jaijaidinbd.com/sports",
    entertainment: "https://www.jaijaidinbd.com/entertainment",
    tech: "https://www.jaijaidinbd.com/information-technology",
    opinion: "https://www.jaijaidinbd.com/open-opinion",
    lifestyle: "https://www.jaijaidinbd.com/life-style",
    crime: "https://www.jaijaidinbd.com/crime",
    politics: "https://www.jaijaidinbd.com/politics",
    countryside: "https://www.jaijaidinbd.com/wholecountry",
    health: "https://www.jaijaidinbd.com/health-",
    literature: "https://www.jaijaidinbd.com/art-and-literature",
    religion: "https://www.jaijaidinbd.com/islam-and-religion",
  },

  dainikAzadi: {
    leading: "https://dainikazadi.net/",
    national: "https://dainikazadi.net/category/nation/",
    international:
      "https://dainikazadi.net/category/today-newspaper/international/",
    business: "https://dainikazadi.net/category/today-newspaper/echonomy/",
    sports: "https://dainikazadi.net/category/sports/",
    entertainment:
      "https://dainikazadi.net/category/today-newspaper/%e0%a6%ac%e0%a6%bf%e0%a6%a8%e0%a7%8b%e0%a6%a6%e0%a6%a8/",
    opinion: "https://dainikazadi.net/sub-editorial/",
    education: "https://dainikazadi.net/category/education/",
    health: "https://dainikazadi.net/category/feature/health/",
    // lifestyle: "https://dainikazadi.net/category/feature/life-style/", // only one items
    feature: "https://dainikazadi.net/feature/",
    countryside: "https://dainikazadi.net/category/today-newspaper/on-village/",
    editorial: "https://dainikazadi.net/category/today-newspaper/editorial/",
  },

  dailyJanakantha: {
    leading: "https://www.dailyjanakantha.com/",
    national: "https://www.dailyjanakantha.com/national/",
    international: "https://www.dailyjanakantha.com/international/",
    business: "https://www.dailyjanakantha.com/economy/",
    sports: "https://www.dailyjanakantha.com/sports/",
    entertainment: "https://www.dailyjanakantha.com/entertainment/",
    tech: "https://www.dailyjanakantha.com/science-technology/",
    opinion: "https://www.dailyjanakantha.com/opinion/",
    lifestyle: "https://www.dailyjanakantha.com/lifestyle/",
    job: "https://www.dailyjanakantha.com/job/",
    politics: "https://www.dailyjanakantha.com/politics/",
    countryside: "https://www.dailyjanakantha.com/bangladesh/",
    health: "https://www.dailyjanakantha.com/health/",
    education: "https://www.dailyjanakantha.com/education/",
  },

  jugantor: {
    leading: "https://www.jugantor.com/",
    national: "https://www.jugantor.com/national",
    international: "https://www.jugantor.com/international",
    business: "https://www.jugantor.com/economics",
    sports: "https://www.jugantor.com/sports",
    entertainment: "https://www.jugantor.com/entertainment",
    tech: "https://www.jugantor.com/tech",
    opinion: "https://www.jugantor.com/editorial",
    lifestyle: "https://www.jugantor.com/lifestyle",
    job: "https://www.jugantor.com/job-seek",
    politics: "https://www.jugantor.com/politics",
    countryside: "https://www.jugantor.com/country-news",
    religion: "https://www.jugantor.com/islam-life",
    education: "https://www.jugantor.com/campus",
  },

  kalbela:{
    leading: "https://www.kalbela.com/",
  },

  kalerKantho: {
    leading: "https://www.kalerkantho.com/",
    national: "https://www.kalerkantho.com/online/national",
    international: "https://www.kalerkantho.com/online/world",
    business: "https://www.kalerkantho.com/online/business",
    sports: "https://www.kalerkantho.com/online/sport",
    entertainment: "https://www.kalerkantho.com/online/entertainment",
    tech: "https://www.kalerkantho.com/feature/techbishaw",
    opinion: "https://www.kalerkantho.com/print-edition/editorial",
    lifestyle: "https://www.kalerkantho.com/online/lifestyle",
    job: "https://www.kalerkantho.com/feature/chakriache",
    politics: "https://www.kalerkantho.com/online/Politics",
    countryside: "https://www.kalerkantho.com/online/country-news",
    religion: "https://www.kalerkantho.com/online/Islamic-lifestylie",
  },

  manabZamin: {
    leading: "https://mzamin.com/",
    national: "https://mzamin.com/category.php?cat=8",
    international: "https://mzamin.com/category.php?cat=5",
    business: "https://mzamin.com/category.php?cat=11",
    sports: "https://mzamin.com/category.php?cat=4",
    entertainment: "https://mzamin.com/category.php?cat=6",
    tech: "https://mzamin.com/category.php?cat=15",
    opinion: "https://mzamin.com/category.php?cat=14",
    health: "https://mzamin.com/category.php?cat=16",
    education: "https://mzamin.com/category.php?cat=10",
    politics: "https://mzamin.com/category.php?cat=24",
  },

  manobKantha:{
    leading: "https://www.manobkantha.com.bd/",
  },

  dailyNayaDiganta: {
    leading: "https://www.dailynayadiganta.com/",
    national: "https://www.dailynayadiganta.com/national/1",
    international: "https://www.dailynayadiganta.com/international/8",
    business: "https://www.dailynayadiganta.com/economics/3",
    sports: "https://www.dailynayadiganta.com/sports/11",
    entertainment: "https://www.dailynayadiganta.com/entertainment/16",
    opinion: "https://www.dailynayadiganta.com/sub-editorial/9",
    feature: "https://www.dailynayadiganta.com/feature/12",
    lifestyle: "https://www.dailynayadiganta.com/lifestyle/15", // layout is different
    politics: "https://www.dailynayadiganta.com/politics/2",
    countryside: "https://www.dailynayadiganta.com/country/7",
    education: "https://www.dailynayadiganta.com/education/22",
  },

  prothomAlo: {
    leading: "https://www.prothomalo.com/",
    national: "https://www.prothomalo.com/bangladesh",
    international: "https://www.prothomalo.com/world",
    business: "https://www.prothomalo.com/business",
    sports: "https://www.prothomalo.com/sports",
    entertainment: "https://www.prothomalo.com/entertainment",
    opinion: "https://www.prothomalo.com/opinion",
    feature: "",
    lifestyle: "https://www.prothomalo.com/lifestyle",
    tech: "https://www.prothomalo.com/technology",
    job: "https://www.prothomalo.com/chakri",
    politics: "https://www.prothomalo.com/politics",
    crime: "https://www.prothomalo.com/bangladesh/crime",
    education: "https://www.prothomalo.com/education",
  },

  protidinerSangbad: {
    leading: "https://www.protidinersangbad.com/",
    national: "https://www.protidinersangbad.com/national",
    international: "https://www.protidinersangbad.com/international",
    business: "https://www.protidinersangbad.com/trade",
    sports: "https://www.protidinersangbad.com/sports",
    entertainment: "https://www.protidinersangbad.com/entertainment",
    tech: "https://www.protidinersangbad.com/science-technology",
    opinion: "https://www.protidinersangbad.com/editorial",
    campus: "https://www.protidinersangbad.com/education-premises",
    health: "https://www.protidinersangbad.com/life-style/health",
    lifestyle: "https://www.protidinersangbad.com/life-style",
    politics: "https://www.protidinersangbad.com/politics",
    literature: "https://www.protidinersangbad.com/art-literature",
    countryside: "https://www.protidinersangbad.com/whole-country",
    corporate: "https://www.protidinersangbad.com/corporate-news",
    job: "https://www.protidinersangbad.com/jobs",
    crime: "https://www.protidinersangbad.com/crime",
  },

  samakal: {
    // samakal is not working. showing- Timeouterror
    leading: "https://samakal.com/",
    national: "https://samakal.com/bangladesh",
    international: "https://samakal.com/international",
    business: "https://samakal.com/economics",
    sports: "https://samakal.com/sports",
    entertainment: "https://samakal.com/entertainment",
    tech: "https://samakal.com/technology",
    opinion: "https://samakal.com/opinion",
    lifestyle: "https://samakal.com/lifestyle",
    politics: "https://samakal.com/politics",
    countryside: "https://samakal.com/whole-country",
    crime: "https://samakal.com/crime",
    literature: "https://samakal.com/sahitto-o-sangskriti",
    education: "https://samakal.com/sub/education",
    job: "https://samakal.com/chakri",
  },

  dailySangram: {
    leading: "https://dailysangram.com/",
    national: "https://dailysangram.com/section/bangladesh",
    international: "https://dailysangram.com/section/international",
    business: "https://dailysangram.com/section/economics",
    sports: "https://dailysangram.com/section/sports",
    tech: "https://dailysangram.com/section/science-technology",
    opinion: "https://dailysangram.com/section/opinion",
    lifestyle: "https://dailysangram.com/section/life-style",
    crime: "https://dailysangram.com/section/bangladesh/crime",
    politics: "https://dailysangram.com/section/bangladesh/politics",
    literature: "https://dailysangram.com/section/literature",
    countryside: "https://dailysangram.com/section/bangladesh/country",
  },

  shomoyEralo: {
    leading: "https://www.shomoyeralo.com/",
  },

  sangbad: {
    leading: "https://sangbad.net.bd/",
    national: "https://sangbad.net.bd/news/national/",
    international: "https://sangbad.net.bd/news/international/",
    business: "https://sangbad.net.bd/news/business/",
    sports: "https://sangbad.net.bd/news/sports/",
    entertainment: "https://sangbad.net.bd/news/entertainment/",
    tech: "https://sangbad.net.bd/news/it/",
    opinion: "https://sangbad.net.bd/opinion/editorial/",
    campus: "https://sangbad.net.bd/news/campus/",
    crime: "https://sangbad.net.bd/news/crime-corruption/",
    politics: "https://sangbad.net.bd/news/politics/",
    literature: "https://sangbad.net.bd/news/culture/",
    countryside: "https://sangbad.net.bd/news/bangladesh/",
  },

  // /** --------------
  //  * ONLINE NEWSPAPERS
  //  * --------------- */
  bbcBangla: {
    leading: "https://www.bbc.com/bengali",
    national: "https://www.bbc.com/bengali/topics/c2dwq2nd40xt",
    // international: "https://www.bbc.com/bengali/topics/c907347rezkt",
    business: "https://www.bbc.com/bengali/topics/cjgn7233zk5t",
    sports: "https://www.bbc.com/bengali/topics/cdr56g57y01t",
    tech: "https://www.bbc.com/bengali/topics/c8y94k95v52t",
    politics: "https://www.bbc.com/bengali/topics/cqywj91rkg6t",
    health: "https://www.bbc.com/bengali/topics/cg7265yyxn1t",
    video: "https://www.bbc.com/bengali/topics/cxy7jg418e7t",
  },
  banglaNews24: {
    leading: "https://www.banglanews24.com/",
    national:
      "https://www.banglanews24.com/category/%E0%A6%9C%E0%A6%BE%E0%A6%A4%E0%A7%80%E0%A7%9F/1",
    international:
      "https://www.banglanews24.com/category/%E0%A6%86%E0%A6%A8%E0%A7%8D%E0%A6%A4%E0%A6%B0%E0%A7%8D%E0%A6%9C%E0%A6%BE%E0%A6%A4%E0%A6%BF%E0%A6%95/4",
    business:
      "https://www.banglanews24.com/category/%E0%A6%85%E0%A6%B0%E0%A7%8D%E0%A6%A5%E0%A6%A8%E0%A7%80%E0%A6%A4%E0%A6%BF-%E0%A6%AC%E0%A7%8D%E0%A6%AF%E0%A6%AC%E0%A6%B8%E0%A6%BE/3",
    sports:
      "https://www.banglanews24.com/category/%E0%A6%96%E0%A7%87%E0%A6%B2%E0%A6%BE/5",
    tech: "https://www.banglanews24.com/category/%E0%A6%A4%E0%A6%A5%E0%A7%8D%E0%A6%AF%E0%A6%AA%E0%A7%8D%E0%A6%B0%E0%A6%AF%E0%A7%81%E0%A6%95%E0%A7%8D%E0%A6%A4%E0%A6%BF/7",
    politics:
      "https://www.banglanews24.com/category/%E0%A6%B0%E0%A6%BE%E0%A6%9C%E0%A6%A8%E0%A7%80%E0%A6%A4%E0%A6%BF/2",
    health:
      "https://www.banglanews24.com/category/%E0%A6%B8%E0%A7%8D%E0%A6%AC%E0%A6%BE%E0%A6%B8%E0%A7%8D%E0%A6%A5%E0%A7%8D%E0%A6%AF/19",
    countryside: "https://www.banglanews24.com/district",
    lifestyle:
      "https://www.banglanews24.com/category/%E0%A6%B2%E0%A6%BE%E0%A6%87%E0%A6%AB%E0%A6%B8%E0%A7%8D%E0%A6%9F%E0%A6%BE%E0%A6%87%E0%A6%B2/12",
    entertainment:
      "https://www.banglanews24.com/category/%E0%A6%AC%E0%A6%BF%E0%A6%A8%E0%A7%8B%E0%A6%A6%E0%A6%A8/6",
    literature:
      "https://www.banglanews24.com/category/%E0%A6%B6%E0%A6%BF%E0%A6%B2%E0%A7%8D%E0%A6%AA-%E0%A6%B8%E0%A6%BE%E0%A6%B9%E0%A6%BF%E0%A6%A4%E0%A7%8D%E0%A6%AF/11",
    education:
      "https://www.banglanews24.com/category/%E0%A6%B6%E0%A6%BF%E0%A6%95%E0%A7%8D%E0%A6%B7%E0%A6%BE/20",
    religion:
      "https://www.banglanews24.com/category/%E0%A6%87%E0%A6%B8%E0%A6%B2%E0%A6%BE%E0%A6%AE/15",
    job: "https://www.banglanews24.com/category/%E0%A6%95%E0%A7%8D%E0%A6%AF%E0%A6%BE%E0%A6%B0%E0%A6%BF%E0%A7%9F%E0%A6%BE%E0%A6%B0/32",
    feature:
      "https://www.banglanews24.com/category/%E0%A6%AB%E0%A6%BF%E0%A6%9A%E0%A6%BE%E0%A6%B0/9",
    corporate:
      "https://www.banglanews24.com/category/%E0%A6%95%E0%A6%B0%E0%A7%8D%E0%A6%AA%E0%A7%8B%E0%A6%B0%E0%A7%87%E0%A6%9F%20%E0%A6%95%E0%A6%B0%E0%A7%8D%E0%A6%A8%E0%A6%BE%E0%A6%B0/1259",
    opinion:
      "https://www.banglanews24.com/category/%E0%A6%AE%E0%A7%81%E0%A6%95%E0%A7%8D%E0%A6%A4%E0%A6%AE%E0%A6%A4/16",
    stock:
      "https://www.banglanews24.com/category/%E0%A6%B6%E0%A7%87%E0%A7%9F%E0%A6%BE%E0%A6%B0%E0%A6%AC%E0%A6%BE%E0%A6%9C%E0%A6%BE%E0%A6%B0/1208",
  },
  jagoNews24: {
    leading: "https://www.jagonews24.com/",
    national: "https://www.jagonews24.com/national",
    international: "https://www.jagonews24.com/international",
    business: "https://www.jagonews24.com/economy",
    sports: "https://www.jagonews24.com/sports",
    tech: "https://www.jagonews24.com/technology",
    politics: "https://www.jagonews24.com/politics",
    health: "https://www.jagonews24.com/health",
    countryside: "https://www.jagonews24.com/country",
    lifestyle: "https://www.jagonews24.com/lifestyle",
    entertainment: "https://www.jagonews24.com/entertainment",
    literature: "https://www.jagonews24.com/literature",
    education: "https://www.jagonews24.com/education",
    religion: "https://www.jagonews24.com/religion",
    job: "https://www.jagonews24.com/jago-jobs",
    feature: "https://www.jagonews24.com/feature",
    campus: "https://www.jagonews24.com/campus",
    opinion: "https://www.jagonews24.com/opinion",
    environment: "https://www.jagonews24.com/agriculture-and-nature",
    video: "https://www.jagonews24.com/video",
  },

  banglaTribune: {
    leading: "https://www.banglatribune.com/",
    national: "https://www.banglatribune.com/national",
    politics: "https://www.banglatribune.com/politics",
    countryside: "https://www.banglatribune.com/country",
    international: "https://www.banglatribune.com/foreign",
    opinion: "https://www.banglatribune.com/columns",
    business: "https://www.banglatribune.com/business",
    entertainment: "https://www.banglatribune.com/entertainment",
    sports: "https://www.banglatribune.com/sport",
    health: "https://www.banglatribune.com/health",
    education: "https://www.banglatribune.com/educations",
    campus: "https://www.banglatribune.com/my-campus",
    lifestyle: "https://www.banglatribune.com/lifestyle",
    tech: "https://www.banglatribune.com/tech-and-gadget",
    job: "https://www.banglatribune.com/jobs",
    crime: "https://www.banglatribune.com/law-and-crime",
    literature: "https://www.banglatribune.com/literature",
  },

  dhakaPost: {
    leading: "https://www.dhakapost.com",
    national: "https://www.dhakapost.com/national",
    politics: "https://www.dhakapost.com/politics",
    business: "https://www.dhakapost.com/economy",
    countryside: "https://www.dhakapost.com/country",
    international: "https://www.dhakapost.com/international",
    sports: "https://www.dhakapost.com/sports",
    entertainment: "https://www.dhakapost.com/entertainment",
    health: "https://www.dhakapost.com/health",
    lifestyle: "https://www.dhakapost.com/lifestyle",
    tech: "https://www.dhakapost.com/technology",
    education: "https://www.dhakapost.com/education",
    job: "https://www.dhakapost.com/jobs-career",
    opinion: "https://www.dhakapost.com/opinion",
    religion: "https://www.dhakapost.com/religion",
    campus: "https://www.dhakapost.com/campus",
    crime: "https://www.dhakapost.com/law-courts",
    environment: "https://www.dhakapost.com/agriculture-and-nature",
  },
};
